/**
 * Shared polling schedule for anything generated by a background AI job
 * (Meta Ads creatives, Social Media posts) — used as a TanStack Query
 * `refetchInterval` instead of Supabase Realtime. Realtime was tried first
 * for Meta Ads' Ad Library, but for a single-tenant admin tool a plain
 * conditional poll is simpler (no channel subscribe/reconnect lifecycle,
 * no dependency on Realtime being enabled on the table) and cheaper (no
 * open websocket connection for as long as the tab is open) — the couple
 * of seconds of extra latency doesn't matter here.
 *
 * Naively polling every few seconds from the moment a row is created
 * wastes most of those requests: image/video generation has a real,
 * code-determined floor before completion is even possible (LLM calls,
 * the provider's own generation time, this app's own poll-and-stitch
 * steps) — see WARMUP_MS below for where each number comes from. Below
 * that floor this returns however long is left until the floor instead of
 * polling immediately; only past it does it settle into a tighter, steady
 * interval.
 */
export interface GenerationPollableRow {
  status: string;
  created_at: string;
}

export function generationRefetchInterval<T extends GenerationPollableRow>(
  rows: T[] | undefined,
  inProgressStatuses: string[],
  warmupMs: (row: T) => number,
  steadyPollMs: (row: T) => number
): number | false {
  const inProgress = (rows || []).filter((r) => inProgressStatuses.includes(r.status));
  if (!inProgress.length) return false;

  const now = Date.now();
  const nextChecks = inProgress.map((row) => {
    const elapsed = now - new Date(row.created_at).getTime();
    const warmup = warmupMs(row);
    return elapsed < warmup ? Math.max(1000, warmup - elapsed) : steadyPollMs(row);
  });
  return Math.min(...nextChecks);
}
