import {
  LayoutDashboard,
  Megaphone,
  Mail,
  Send,
  Mic,
  Share2,
  Settings,
  BarChart,
  Users,
  Image as ImageIcon,
  BookOpen,
  Calendar,
  Link,
  CreditCard,
  Bot,
  FileEdit,
  Clock,
  TrendingUp,
  Search,
  History,
  RefreshCw,
  PieChart,
  Target,
  Wand2,
  ListOrdered,
  PlusCircle,
  CheckCircle,
  PlayCircle,
  BarChart2,
  FileText,
} from "lucide-react";
import { NavItem, ProductModule } from "@/types";
import { ROUTES } from "./routes";

export const PRIMARY_NAV_ITEMS: NavItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    href: ROUTES.DASHBOARD.HOME,
    icon: LayoutDashboard,
    module: "dashboard",
  },
  {
    id: "metaAds",
    label: "Meta Ads",
    href: ROUTES.META_ADS.OVERVIEW,
    icon: Megaphone,
    module: "metaAds",
  },
  {
    id: "newsletter",
    label: "Newsletter",
    href: ROUTES.NEWSLETTER.DASHBOARD,
    icon: Mail,
    module: "newsletter",
  },
  {
    id: "outreach",
    label: "Outreach",
    href: ROUTES.OUTREACH.DASHBOARD,
    icon: Send,
    module: "outreach",
  },
  {
    id: "voice",
    label: "Voice Agents",
    href: ROUTES.VOICE.OVERVIEW,
    icon: Mic,
    module: "voice",
  },
  {
    id: "social",
    label: "Social Media",
    href: ROUTES.SOCIAL.OVERVIEW,
    icon: Share2,
    module: "social",
  },
  {
    id: "settings",
    label: "Settings",
    href: ROUTES.SETTINGS.WORKSPACE,
    icon: Settings,
    module: "settings",
  },
];

export const SECONDARY_NAV_ITEMS: Record<
  ProductModule,
  Omit<NavItem, "module">[]
> = {
  dashboard: [],
  metaAds: [
    {
      id: "ma-overview",
      label: "Overview",
      href: ROUTES.META_ADS.OVERVIEW,
      icon: LayoutDashboard,
    },
    {
      id: "ma-create",
      label: "Create Ad",
      href: ROUTES.META_ADS.CREATE,
      icon: PlusCircle,
    },
    {
      id: "ma-approval",
      label: "Approval",
      href: ROUTES.META_ADS.APPROVAL,
      icon: CheckCircle,
    },
    {
      id: "ma-campaigns",
      label: "Campaign Setup",
      href: ROUTES.META_ADS.CAMPAIGNS,
      icon: Settings,
    },
    {
      id: "ma-live-campaigns",
      label: "Live Campaigns",
      href: ROUTES.META_ADS.LIVE_CAMPAIGNS,
      icon: PlayCircle,
    },
    {
      id: "ma-reports",
      label: "Reports",
      href: ROUTES.META_ADS.REPORTS,
      icon: FileText,
    },
    {
      id: "ma-report-analysis",
      label: "Report Analysis",
      href: ROUTES.META_ADS.REPORT_ANALYSIS,
      icon: BarChart2,
    },
    {
      id: "ma-leads",
      label: "Lead Responses",
      href: ROUTES.META_ADS.LEADS,
      icon: Users,
    },
  ],
  newsletter: [
    {
      id: "nl-dashboard",
      label: "Dashboard",
      href: ROUTES.NEWSLETTER.DASHBOARD,
      icon: LayoutDashboard,
    },
    {
      id: "nl-generate",
      label: "Generate Newsletter",
      href: ROUTES.NEWSLETTER.GENERATE,
      icon: FileEdit,
    },
    {
      id: "nl-campaigns",
      label: "Create Campaign",
      href: ROUTES.NEWSLETTER.CAMPAIGNS,
      icon: Megaphone,
    },
    {
      id: "nl-history",
      label: "History",
      href: ROUTES.NEWSLETTER.HISTORY,
      icon: Clock,
    },
    {
      id: "nl-services",
      label: "Manage Services",
      href: ROUTES.NEWSLETTER.SERVICES,
      icon: Settings,
    },
  ],
  outreach: [
    {
      id: "or-dashboard",
      label: "Dashboard",
      href: ROUTES.OUTREACH.DASHBOARD,
      icon: LayoutDashboard,
    },
    {
      id: "or-messages",
      label: "Email Messages",
      href: ROUTES.OUTREACH.MESSAGES,
      icon: Mail,
    },
    {
      id: "or-analytics",
      label: "Outreach Analytics",
      href: ROUTES.OUTREACH.ANALYTICS,
      icon: TrendingUp,
    },
    {
      id: "or-scraper",
      label: "Lead Scraper",
      href: ROUTES.OUTREACH.SCRAPER,
      icon: Search,
    },
    {
      id: "or-scraper-history",
      label: "Scraper History",
      href: ROUTES.OUTREACH.SCRAPER_HISTORY,
      icon: History,
    },
    {
      id: "or-reset-status",
      label: "Reset Lead Status",
      href: ROUTES.OUTREACH.RESET_STATUS,
      icon: RefreshCw,
    },
  ],
  voice: [
    {
      id: "va-overview",
      label: "Overview",
      href: ROUTES.VOICE.OVERVIEW,
      icon: LayoutDashboard,
    },
    { id: "va-agents", label: "Agents", href: ROUTES.VOICE.AGENTS, icon: Bot },
    {
      id: "va-kb",
      label: "Knowledge Base",
      href: ROUTES.VOICE.KNOWLEDGE_BASE,
      icon: BookOpen,
    },
    { id: "va-calls", label: "Calls", href: ROUTES.VOICE.CALLS, icon: Mic },
    {
      id: "va-analytics",
      label: "Analytics",
      href: ROUTES.VOICE.ANALYTICS,
      icon: BarChart,
    },
  ],
  social: [
    {
      id: "sm-overview",
      label: "Overview",
      href: ROUTES.SOCIAL.OVERVIEW,
      icon: LayoutDashboard,
    },
    {
      id: "sm-posts",
      label: "Posts",
      href: ROUTES.SOCIAL.POSTS,
      icon: Megaphone,
    },
    {
      id: "sm-media",
      label: "Media",
      href: ROUTES.SOCIAL.MEDIA,
      icon: ImageIcon,
    },
    {
      id: "sm-calendar",
      label: "Calendar",
      href: ROUTES.SOCIAL.CALENDAR,
      icon: Calendar,
    },
    {
      id: "sm-analytics",
      label: "Analytics",
      href: ROUTES.SOCIAL.ANALYTICS,
      icon: BarChart,
    },
  ],
  settings: [
    {
      id: "st-workspace",
      label: "Workspace",
      href: ROUTES.SETTINGS.WORKSPACE,
      icon: LayoutDashboard,
    },
    {
      id: "st-users",
      label: "Users",
      href: ROUTES.SETTINGS.USERS,
      icon: Users,
    },
    {
      id: "st-accounts",
      label: "Connected Accounts",
      href: ROUTES.SETTINGS.CONNECTED_ACCOUNTS,
      icon: Link,
    },
    {
      id: "st-providers",
      label: "AI Providers",
      href: ROUTES.SETTINGS.AI_PROVIDERS,
      icon: Bot,
    },
    {
      id: "st-billing",
      label: "Billing",
      href: ROUTES.SETTINGS.BILLING,
      icon: CreditCard,
    },
  ],
};
