-- Add AI-specific metric columns to meta_self_ad_metrics
ALTER TABLE public.meta_self_ad_metrics
ADD COLUMN IF NOT EXISTS ad_text TEXT,
ADD COLUMN IF NOT EXISTS media_url TEXT,
ADD COLUMN IF NOT EXISTS format TEXT,
ADD COLUMN IF NOT EXISTS hook_rate NUMERIC(5,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS hold_rate NUMERIC(5,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS roas NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cpa NUMERIC(10,2) DEFAULT 0;
